# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: contratos_incompativel/emprestimos.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'contratos_incompativel/emprestimos.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(contratos_incompativel/emprestimos.proto\x12\x19\x62iblioteca.emprestimos.v1\"\xc6\x01\n\nEmprestimo\x12\x0e\n\x06\x63odigo\x18\x01 \x01(\t\x12\x0c\n\x04isbn\x18\x02 \x01(\t\x12\x0e\n\x06titulo\x18\x03 \x01(\t\x12\x0f\n\x07unidade\x18\x04 \x01(\t\x12\x15\n\remprestado_em\x18\x05 \x01(\t\x12\x15\n\rprevisto_para\x18\x06 \x01(\t\x12\x14\n\x0c\x64\x65volvido_em\x18\x07 \x01(\t\x12\x35\n\x08situacao\x18\x08 \x01(\x0e\x32#.biblioteca.emprestimos.v1.Situacao\"u\n\x1aRegistrarEmprestimoRequest\x12\x0c\n\x04isbn\x18\x01 \x01(\t\x12\x0e\n\x06leitor\x18\x02 \x01(\t\x12\x0c\n\x04\x64ias\x18\x03 \x01(\t\x12\x1a\n\x12\x63have_idempotencia\x18\x04 \x01(\t\x12\x0f\n\x07unidade\x18\x05 \x01(\t*R\n\x08Situacao\x12\x1a\n\x16SITUACAO_NAO_INFORMADA\x10\x00\x12\x12\n\x0eSITUACAO_ATIVO\x10\x01\x12\x16\n\x12SITUACAO_DEVOLVIDO\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contratos_incompativel.emprestimos_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SITUACAO']._serialized_start=391
  _globals['_SITUACAO']._serialized_end=473
  _globals['_EMPRESTIMO']._serialized_start=72
  _globals['_EMPRESTIMO']._serialized_end=270
  _globals['_REGISTRAREMPRESTIMOREQUEST']._serialized_start=272
  _globals['_REGISTRAREMPRESTIMOREQUEST']._serialized_end=389
# @@protoc_insertion_point(module_scope)
