import os
from pathlib import Path

RAIZ_DO_PROJETO = Path(__file__).resolve().parent.parent

SERVIDOR_HOST = os.getenv("GRPC_HOST", "localhost")
SERVIDOR_PORTA = int(os.getenv("GRPC_PORTA", "50051"))
WORKERS_PADRAO = int(os.getenv("GRPC_WORKERS", "8"))

DEADLINE_PADRAO = 1.0
TAMANHO_MAXIMO_DA_MENSAGEM = 4 * 1024 * 1024
CHAMADAS_CONCORRENTES_MAXIMAS = 64

PRAZO_EM_DIAS = 14
PRAZO_MINIMO_EM_DIAS = 1
PRAZO_MAXIMO_EM_DIAS = 30
VALOR_DA_MULTA_POR_DIA = 0.50

CUSTO_POR_CODIGO_NA_MULTA = 0.03
LIMITE_DE_CODIGOS_NA_MULTA = 500
LIMITE_PADRAO_DA_LISTAGEM = 50

PASTA_DE_LOGS = RAIZ_DO_PROJETO / "logs"
PASTA_DE_DOCS = RAIZ_DO_PROJETO / "docs"

CHAVE_DE_CORRELACAO = "x-correlacao-id"
CHAVE_DE_TENTATIVA = "x-tentativa"
