# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from contratos_legado import emprestimos_pb2 as contratos__legado_dot_emprestimos__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in contratos_legado/emprestimos_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EmprestimosStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegistrarEmprestimo = channel.unary_unary(
                '/biblioteca.emprestimos.v1.Emprestimos/RegistrarEmprestimo',
                request_serializer=contratos__legado_dot_emprestimos__pb2.RegistrarEmprestimoRequest.SerializeToString,
                response_deserializer=contratos__legado_dot_emprestimos__pb2.RegistrarEmprestimoResponse.FromString,
                _registered_method=True)
        self.ConsultarEmprestimo = channel.unary_unary(
                '/biblioteca.emprestimos.v1.Emprestimos/ConsultarEmprestimo',
                request_serializer=contratos__legado_dot_emprestimos__pb2.ConsultarEmprestimoRequest.SerializeToString,
                response_deserializer=contratos__legado_dot_emprestimos__pb2.ConsultarEmprestimoResponse.FromString,
                _registered_method=True)
        self.RegistrarDevolucao = channel.unary_unary(
                '/biblioteca.emprestimos.v1.Emprestimos/RegistrarDevolucao',
                request_serializer=contratos__legado_dot_emprestimos__pb2.RegistrarDevolucaoRequest.SerializeToString,
                response_deserializer=contratos__legado_dot_emprestimos__pb2.RegistrarDevolucaoResponse.FromString,
                _registered_method=True)
        self.CalcularMultas = channel.unary_unary(
                '/biblioteca.emprestimos.v1.Emprestimos/CalcularMultas',
                request_serializer=contratos__legado_dot_emprestimos__pb2.CalcularMultasRequest.SerializeToString,
                response_deserializer=contratos__legado_dot_emprestimos__pb2.CalcularMultasResponse.FromString,
                _registered_method=True)
        self.ListarEmprestimos = channel.unary_stream(
                '/biblioteca.emprestimos.v1.Emprestimos/ListarEmprestimos',
                request_serializer=contratos__legado_dot_emprestimos__pb2.ListarEmprestimosRequest.SerializeToString,
                response_deserializer=contratos__legado_dot_emprestimos__pb2.Emprestimo.FromString,
                _registered_method=True)


class EmprestimosServicer:
    """Missing associated documentation comment in .proto file."""

    def RegistrarEmprestimo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsultarEmprestimo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegistrarDevolucao(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalcularMultas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarEmprestimos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmprestimosServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegistrarEmprestimo': grpc.unary_unary_rpc_method_handler(
                    servicer.RegistrarEmprestimo,
                    request_deserializer=contratos__legado_dot_emprestimos__pb2.RegistrarEmprestimoRequest.FromString,
                    response_serializer=contratos__legado_dot_emprestimos__pb2.RegistrarEmprestimoResponse.SerializeToString,
            ),
            'ConsultarEmprestimo': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarEmprestimo,
                    request_deserializer=contratos__legado_dot_emprestimos__pb2.ConsultarEmprestimoRequest.FromString,
                    response_serializer=contratos__legado_dot_emprestimos__pb2.ConsultarEmprestimoResponse.SerializeToString,
            ),
            'RegistrarDevolucao': grpc.unary_unary_rpc_method_handler(
                    servicer.RegistrarDevolucao,
                    request_deserializer=contratos__legado_dot_emprestimos__pb2.RegistrarDevolucaoRequest.FromString,
                    response_serializer=contratos__legado_dot_emprestimos__pb2.RegistrarDevolucaoResponse.SerializeToString,
            ),
            'CalcularMultas': grpc.unary_unary_rpc_method_handler(
                    servicer.CalcularMultas,
                    request_deserializer=contratos__legado_dot_emprestimos__pb2.CalcularMultasRequest.FromString,
                    response_serializer=contratos__legado_dot_emprestimos__pb2.CalcularMultasResponse.SerializeToString,
            ),
            'ListarEmprestimos': grpc.unary_stream_rpc_method_handler(
                    servicer.ListarEmprestimos,
                    request_deserializer=contratos__legado_dot_emprestimos__pb2.ListarEmprestimosRequest.FromString,
                    response_serializer=contratos__legado_dot_emprestimos__pb2.Emprestimo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'biblioteca.emprestimos.v1.Emprestimos', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('biblioteca.emprestimos.v1.Emprestimos', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Emprestimos:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegistrarEmprestimo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/biblioteca.emprestimos.v1.Emprestimos/RegistrarEmprestimo',
            contratos__legado_dot_emprestimos__pb2.RegistrarEmprestimoRequest.SerializeToString,
            contratos__legado_dot_emprestimos__pb2.RegistrarEmprestimoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsultarEmprestimo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/biblioteca.emprestimos.v1.Emprestimos/ConsultarEmprestimo',
            contratos__legado_dot_emprestimos__pb2.ConsultarEmprestimoRequest.SerializeToString,
            contratos__legado_dot_emprestimos__pb2.ConsultarEmprestimoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegistrarDevolucao(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/biblioteca.emprestimos.v1.Emprestimos/RegistrarDevolucao',
            contratos__legado_dot_emprestimos__pb2.RegistrarDevolucaoRequest.SerializeToString,
            contratos__legado_dot_emprestimos__pb2.RegistrarDevolucaoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalcularMultas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/biblioteca.emprestimos.v1.Emprestimos/CalcularMultas',
            contratos__legado_dot_emprestimos__pb2.CalcularMultasRequest.SerializeToString,
            contratos__legado_dot_emprestimos__pb2.CalcularMultasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarEmprestimos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/biblioteca.emprestimos.v1.Emprestimos/ListarEmprestimos',
            contratos__legado_dot_emprestimos__pb2.ListarEmprestimosRequest.SerializeToString,
            contratos__legado_dot_emprestimos__pb2.Emprestimo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
