[[Alunos]]
id = 1
nome = "Samuel Resende"
idade = 23
habilidades = ["Python", "SQL"]
matriculado = true

[[Alunos]]
id = 2
nome = "Carlos Souza"
idade = 35
habilidades = ["JavaScript", "React"]
matriculado = false